apiVersion: apps/v1
kind: Deployment

metadata:
  name: telemetry-collector
  namespace: {{ .Values.namespace }}

spec:

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: telemetry-collector

  template:

    metadata:
      labels:
        app: telemetry-collector

    spec:
      imagePullSecrets:
      - name: ghcr-secret

      containers:

      - name: collector

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
      name: telemetry-config
        ports:
        - containerPort: 8000
