apiVersion: v1
kind: Service

metadata:
  name: telemetry-service
  namespace: {{ .Values.namespace }}

spec:

  selector:
    app: telemetry-collector

  ports:

  - port: {{ .Values.service.port }}
    targetPort: 8000

  type: {{ .Values.service.type }}
